### ISSUE TITLE
Request regarding demo_latent_space

### ISSUE THREAD

**Issue by kosuke55** [marian42/shapegan#4]
Thank you for a great work.
Is it possible to share `sdf_net_latent_codes.to` to run `demo_latent_space.py`?
Also I need `sdf_points.to` and `sdf_values.to` to run `train_sdf_autodecoder.py`, how can I get it?

**Comment by marian42** [comment]
I just uploaded the files and I created an explanation on how to run `demo_latent_space.py`. It's at the bottom of the project readme file.

**Comment by kosuke55** [comment]
Thank you very much!

**Comment by Haian-Jin** [comment]
Thank you very much for your wonderful work!
I still don't know how to find  `sdf_points.to` and `sdf_values.to`  to train the DeepSDF. Can you please give more explanation?

**Comment by Haian-Jin** [comment]
> I just uploaded the files and I created an explanation on how to run `demo_latent_space.py`. It's at the bottom of the project readme file.

Thank you very much for your wonderful work!
I still don't know how to find `sdf_points.to` and `sdf_values.to` to train the DeepSDF. Can you please give more explanation?
