### ISSUE TITLE
Visualization Scripts for the point-based GAN

### ISSUE THREAD

**Issue by ckxz** [marian42/shapegan#5]
Hi Marian,
Is there any chance you could upload the visualization scripts for the point-based GAN? I am precisely training the point_sdf_net model and would like to see what comes out from it.
Cheers!

**Comment by marian42** [comment]
I have to admit that I wrote everything in this repository, except for the point-based GANs. These have been implemented by @rusty1s. We haven't done any of the animated visualizations with the point-based GANs.

We made the graphics for the paper by saving meshes and rendering them with Blender. @rusty1s, do you happen to have the code that was used to save these meshes?

Alternatively, you can try to get the `train_point_gan.py` script to work with the mesh viewer that is used in the rest of the project. A first step for that would be to replace the `SDFGenerator` in `train_point_gan.py` with the `model.sdf_net.SDFNet` class that is used everywhere else. The two classes do the same thing, we just worked on this in parallel. I know this is inconvenient, sorry!

**Comment by ckxz** [comment]
What I'm interested in are actually the meshes. @rusty1s, I'd be truly thankful if you could share the code you used to saving them. Otherwise, I'll proceed and try what you suggest @marian42.

**Comment by rusty1s** [comment]
The easiest way to get this working is to copy-paste the [`get_mesh`](https://github.com/marian42/shapegan/blob/master/model/sdf_net.py#L97-L112) functionality to the [`SDFGenerator`](https://github.com/marian42/shapegan/blob/master/model/point_sdf_net.py#L50) class, just like I did [here](https://github.com/marian42/shapegan/blob/point_sdf/point_sdf/generator.py#L87-L120) in the `point_sdf` branch.

**Comment by ckxz** [comment]
Thanks @rusty1s and @marian42 . I have it up and running.
